### GENERAMOS EL TOKEN DE USUARIO ###
# @name generate
POST {{$dotenv HOST}}/auth/token
Content-Type: {{$dotenv CONTENT_TYPE}}

{
    "dni": "{{$dotenv USERNAME}}",
    "password": "{{$dotenv PASSWORD}}",
    "expires": true,
    "time": "1d"
}

### OBTENEMOS EL TOKEN DE AUTORIZACIÓN ###
@authToken = {{generate.response.body.token}}

### OBTENEMOS TODOS LOS MÓDULOS ###
GET {{$dotenv HOST}}/admin/modulos
    ?page=1
    &pageSize=10
Authorization: {{authToken}}
Content-Type: {{$dotenv CONTENT_TYPE}}
Source: {{$dotenv SOURCE}}
Origin: {{$dotenv ORIGIN}}
Ip: {{$dotenv IP}}
Device: {{$dotenv DEVICE}}
Browser: {{$dotenv BROWSER}}

### CREAMOS UN MÓDULO ###
# @name create
POST {{$dotenv HOST}}/admin/modulos
Authorization: {{authToken}}
Content-Type: {{$dotenv CONTENT_TYPE}}
Source: {{$dotenv SOURCE}}
Origin: {{$dotenv ORIGIN}}
Ip: {{$dotenv IP}}
Device: {{$dotenv DEVICE}}
Browser: {{$dotenv BROWSER}}

{
    "orden": 1,
    "tag": "admin",
    "nombre": "Administrativo",
    "descripcion": "Módulo para gestionar la administración de la App",
    "type": "collapse",
    "icon": "security",
    "children": [
		{    
			"orden": 1,
			"tag": "acciones",
			"nombre": "Acciones",
			"descripcion": "Submódulo para gestionar las acciones en un módulo o submódulo.",
			"type": "item",
			"url": "/admin/acciones"
		},		
		{
			"orden": 2,
			"tag": "modulos",
			"nombre": "Módulos",
			"descripcion": "Submódulo para gestionar los módulos y submódulos de la App.",
			"type": "item",
			"url": "/admin/modulos"
		}
	]
}

### ID DE MÓDULO ###
@idModulo = {{create.response.body.modulo._id}}
# @idModulo = 5fd6e73c5791f62e30e78455

### OBTENEMOS DATOS DE UN MÓDULO ###
GET {{$dotenv HOST}}/admin/modulos/{{idModulo}}
Authorization: {{authToken}}
Content-Type: {{$dotenv CONTENT_TYPE}}
Source: {{$dotenv SOURCE}}
Origin: {{$dotenv ORIGIN}}
Ip: {{$dotenv IP}}
Device: {{$dotenv DEVICE}}
Browser: {{$dotenv BROWSER}}

### ACTUALIZAMOS DATOS DE UN MÓDULO ###
PUT {{$dotenv HOST}}/admin/modulos/{{idModulo}}
Authorization: {{authToken}}
Content-Type: {{$dotenv CONTENT_TYPE}}
Source: {{$dotenv SOURCE}}
Origin: {{$dotenv ORIGIN}}
Ip: {{$dotenv IP}}
Device: {{$dotenv DEVICE}}
Browser: {{$dotenv BROWSER}}

{
    "orden": 3,
    "tag": "test_actualizado",
    "nombre": "Test Actualizado",
    "descripcion": "descripcion del módulo test actualizado",
    "type": "item"
}

### ELIMINAMOS DATOS DE UN MÓDULO ###
DELETE {{$dotenv HOST}}/admin/modulos/{{idModulo}}
Authorization: {{authToken}}
Content-Type: {{$dotenv CONTENT_TYPE}}
Source: {{$dotenv SOURCE}}
Origin: {{$dotenv ORIGIN}}
Ip: {{$dotenv IP}}
Device: {{$dotenv DEVICE}}
Browser: {{$dotenv BROWSER}}