### GENERAMOS EL TOKEN DE USUARIO ###
# @name generate
POST {{$dotenv HOST}}/auth/token
Content-Type: {{$dotenv CONTENT_TYPE}}

{
    "dni": "{{$dotenv USERNAME}}",
    "password": "{{$dotenv PASSWORD}}",
    "expires": true,
    "time": "1d"
}

### OBTENEMOS EL TOKEN DE AUTORIZACIÓN ###
@authToken = {{generate.response.body.token}}

### OBTENEMOS TODOS LOS USUARIOS ###
GET {{$dotenv HOST}}/usuarios
    ?page=1
    &pageSize=10
Authorization: {{authToken}}
Content-Type: {{$dotenv CONTENT_TYPE}}
Source: {{$dotenv SOURCE}}
Origin: {{$dotenv ORIGIN}}
Ip: {{$dotenv IP}}
Device: {{$dotenv DEVICE}}
Browser: {{$dotenv BROWSER}}

### CREAMOS UN USUARIO ###
# @name create
POST {{$dotenv HOST}}/usuarios
Authorization: {{authToken}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Source: {{$dotenv SOURCE}}
Origin: {{$dotenv ORIGIN}}
Ip: {{$dotenv IP}}
Device: {{$dotenv DEVICE}}
Browser: {{$dotenv BROWSER}}

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="nombres"

Nombres
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="apellidos"

Apellidos
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="dni"

12345678
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="celular"

987654321
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="genero"

M
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="password"

secret
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="rol"

624e5aeceea7b0820412313
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="avatar.jpg"
Content-Type: image/jpeg

< ./avatar.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### ID DE USUARIO ###
@idUsuario = {{create.response.body.usuario._id}}

### OBTENEMOS DATOS DE UN USUARIO ###
GET {{$dotenv HOST}}/usuarios/{{idUsuario}}
Authorization: {{authToken}}
Content-Type: {{$dotenv CONTENT_TYPE}}
Source: {{$dotenv SOURCE}}
Origin: {{$dotenv ORIGIN}}
Ip: {{$dotenv IP}}
Device: {{$dotenv DEVICE}}
Browser: {{$dotenv BROWSER}}

### ACTUALIZAMOS DATOS DE UN USUARIO ###
PUT {{$dotenv HOST}}/usuarios/{{idUsuario}}
Authorization: {{authToken}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Source: {{$dotenv SOURCE}}
Origin: {{$dotenv ORIGIN}}
Ip: {{$dotenv IP}}
Device: {{$dotenv DEVICE}}
Browser: {{$dotenv BROWSER}}

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="nombres"

NombresAct
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="apellidos"

ApellidosAct
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="dni"

12345679
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="celular"

123456789
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="genero"

F
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="avatar.jpg"
Content-Type: image/jpeg

< ./avatar.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### ELIMINAMOS DATOS DE UN USUARIO ###
DELETE {{$dotenv HOST}}/usuarios/{{idUsuario}}
Authorization: {{authToken}}
Content-Type: {{$dotenv CONTENT_TYPE}}
Source: {{$dotenv SOURCE}}
Origin: {{$dotenv ORIGIN}}
Ip: {{$dotenv IP}}
Device: {{$dotenv DEVICE}}
Browser: {{$dotenv BROWSER}}