### GENERAMOS EL TOKEN DE USUARIO ###
# @name generate
POST {{$dotenv HOST}}/auth/token
Content-Type: {{$dotenv CONTENT_TYPE}}

{
    "dni": "{{$dotenv USERNAME}}",
    "password": "{{$dotenv PASSWORD}}",
    "expires": true,
    "time": "1d"
}

### OBTENEMOS EL TOKEN DE AUTORIZACIÓN ###
@authToken = {{generate.response.body.token}}

### OBTENEMOS TODOS LOS DEPARTAMENTOS ###
GET {{$dotenv HOST}}/ubigeo/departamentos
    ?page=1
    &pageSize=10
Authorization: {{authToken}}
Content-Type: {{$dotenv CONTENT_TYPE}}
Source: {{$dotenv SOURCE}}
Origin: {{$dotenv ORIGIN}}
Ip: {{$dotenv IP}}
Device: {{$dotenv DEVICE}}
Browser: {{$dotenv BROWSER}}

### CREAMOS UN DEPARTAMENTO ###
# @name create
POST {{$dotenv HOST}}/ubigeo/departamentos
Authorization: {{authToken}}
Content-Type: {{$dotenv CONTENT_TYPE}}
Source: {{$dotenv SOURCE}}
Origin: {{$dotenv ORIGIN}}
Ip: {{$dotenv IP}}
Device: {{$dotenv DEVICE}}
Browser: {{$dotenv BROWSER}}

{
    "codigo": "22",
    "nombre": "SAN MARTIN"
}

### ID DE DEPARTAMENTO ###
@id = {{create.response.body.departamento._id}}

### OBTENEMOS DATOS DE UN DEPARTAMENTO ###
GET {{$dotenv HOST}}/ubigeo/departamentos/{{id}}
Authorization: {{authToken}}
Content-Type: {{$dotenv CONTENT_TYPE}}
Source: {{$dotenv SOURCE}}
Origin: {{$dotenv ORIGIN}}
Ip: {{$dotenv IP}}
Device: {{$dotenv DEVICE}}
Browser: {{$dotenv BROWSER}}

### ACTUALIZAMOS DATOS DE UN DEPARTAMENTO ###
PUT {{$dotenv HOST}}/ubigeo/departamentos/{{id}}
Authorization: {{authToken}}
Content-Type: {{$dotenv CONTENT_TYPE}}
Source: {{$dotenv SOURCE}}
Origin: {{$dotenv ORIGIN}}
Ip: {{$dotenv IP}}
Device: {{$dotenv DEVICE}}
Browser: {{$dotenv BROWSER}}

{
    "codigo": "22",
    "nombre": "SAN MARTIN ACTUALIZADO"
}

### ELIMINAMOS UN DEPARTAMENTO ###
DELETE {{$dotenv HOST}}/ubigeo/departamentos/{{id}}
Authorization: {{authToken}}
Content-Type: {{$dotenv CONTENT_TYPE}}
Source: {{$dotenv SOURCE}}
Origin: {{$dotenv ORIGIN}}
Ip: {{$dotenv IP}}
Device: {{$dotenv DEVICE}}
Browser: {{$dotenv BROWSER}}