### GENERAMOS EL TOKEN DE USUARIO ###
# @name generate
POST {{$dotenv HOST}}/auth/token
Content-Type: {{$dotenv CONTENT_TYPE}}

{
    "dni": "{{$dotenv USERNAME}}",
    "password": "{{$dotenv PASSWORD}}",
    "expires": true,
    "time": "1d"
}

### OBTENEMOS EL TOKEN DE AUTORIZACIÓN ###
@authToken = {{generate.response.body.token}}

### OBTENEMOS TODOS LOS DISTRITOS ###
GET {{$dotenv HOST}}/ubigeo/distritos
    ?page=1
    &pageSize=10
Authorization: {{authToken}}
Content-Type: {{$dotenv CONTENT_TYPE}}
Source: {{$dotenv SOURCE}}
Origin: {{$dotenv ORIGIN}}
Ip: {{$dotenv IP}}
Device: {{$dotenv DEVICE}}
Browser: {{$dotenv BROWSER}}

### CREAMOS UN DISTRITO ###
# @name create
POST {{$dotenv HOST}}/ubigeo/distritos
Authorization: {{authToken}}
Content-Type: {{$dotenv CONTENT_TYPE}}
Source: {{$dotenv SOURCE}}
Origin: {{$dotenv ORIGIN}}
Ip: {{$dotenv IP}}
Device: {{$dotenv DEVICE}}
Browser: {{$dotenv BROWSER}}

{
    "codigo": "01",
    "nombre": "SAN MARTIN",
    "provincia": "01",
    "departamento": "22"
}

### ID DE DISTRITO ###
@id = {{create.response.body.distrito._id}}

### OBTENEMOS DATOS DE UN DISTRITO ###
GET {{$dotenv HOST}}/ubigeo/distritos/{{id}}
Authorization: {{authToken}}
Content-Type: {{$dotenv CONTENT_TYPE}}
Source: {{$dotenv SOURCE}}
Origin: {{$dotenv ORIGIN}}
Ip: {{$dotenv IP}}
Device: {{$dotenv DEVICE}}
Browser: {{$dotenv BROWSER}}

### ACTUALIZAMOS DATOS DE UN DISTRITO ###
PUT {{$dotenv HOST}}/ubigeo/distritos/{{id}}
Authorization: {{authToken}}
Content-Type: {{$dotenv CONTENT_TYPE}}
Source: {{$dotenv SOURCE}}
Origin: {{$dotenv ORIGIN}}
Ip: {{$dotenv IP}}
Device: {{$dotenv DEVICE}}
Browser: {{$dotenv BROWSER}}

{
    "codigo": "01",
    "nombre": "SAN MARTIN ACTUALIZADO",
    "provincia": "01",
    "departamento": "22"
}

### ELIMINAMOS UN DISTRITO ###
DELETE {{$dotenv HOST}}/ubigeo/distritos/{{id}}
Authorization: {{authToken}}
Content-Type: {{$dotenv CONTENT_TYPE}}
Source: {{$dotenv SOURCE}}
Origin: {{$dotenv ORIGIN}}
Ip: {{$dotenv IP}}
Device: {{$dotenv DEVICE}}
Browser: {{$dotenv BROWSER}}