### GENERAMOS EL TOKEN DE USUARIO ###
# @name generate
POST {{$dotenv HOST}}/auth/token
Content-Type: {{$dotenv CONTENT_TYPE}}

{
    "dni": "{{$dotenv USERNAME}}",
    "password": "{{$dotenv PASSWORD}}",
    "expires": true,
    "time": "1d"
}

### OBTENEMOS EL TOKEN DE AUTORIZACIÓN ###
@authToken = {{generate.response.body.token}}

### OBTENEMOS TODAS LAS PROVINCIAS ###
GET {{$dotenv HOST}}/ubigeo/provincias
    ?page=1
    &pageSize=10
Authorization: {{authToken}}
Content-Type: {{$dotenv CONTENT_TYPE}}
Source: {{$dotenv SOURCE}}
Origin: {{$dotenv ORIGIN}}
Ip: {{$dotenv IP}}
Device: {{$dotenv DEVICE}}
Browser: {{$dotenv BROWSER}}

### CREAMOS UNA PROVINCIA ###
# @name create
POST {{$dotenv HOST}}/ubigeo/provincias
Authorization: {{authToken}}
Content-Type: {{$dotenv CONTENT_TYPE}}
Source: {{$dotenv SOURCE}}
Origin: {{$dotenv ORIGIN}}
Ip: {{$dotenv IP}}
Device: {{$dotenv DEVICE}}
Browser: {{$dotenv BROWSER}}

{
    "codigo": "01",
    "nombre": "SAN MARTIN",
    "departamento": "22",
}

### ID DE PROVINCIA ###
@id = {{create.response.body.provincia._id}}

### OBTENEMOS DATOS DE UNA PROVINCIA ###
GET {{$dotenv HOST}}/ubigeo/provincias/{{id}}
Authorization: {{authToken}}
Content-Type: {{$dotenv CONTENT_TYPE}}
Source: {{$dotenv SOURCE}}
Origin: {{$dotenv ORIGIN}}
Ip: {{$dotenv IP}}
Device: {{$dotenv DEVICE}}
Browser: {{$dotenv BROWSER}}

### ACTUALIZAMOS DATOS DE UNA PROVINCIA ###
PUT {{$dotenv HOST}}/ubigeo/provincias/{{id}}
Authorization: {{authToken}}
Content-Type: {{$dotenv CONTENT_TYPE}}
Source: {{$dotenv SOURCE}}
Origin: {{$dotenv ORIGIN}}
Ip: {{$dotenv IP}}
Device: {{$dotenv DEVICE}}
Browser: {{$dotenv BROWSER}}

{
    "codigo": "01",
    "nombre": "SAN MARTIN ACTUALIZADO",
    "departamento": "22",
}

### ELIMINAMOS UNA PROVINCIA ###
DELETE {{$dotenv HOST}}/ubigeo/provincias/{{id}}
Authorization: {{authToken}}
Content-Type: {{$dotenv CONTENT_TYPE}}
Source: {{$dotenv SOURCE}}
Origin: {{$dotenv ORIGIN}}
Ip: {{$dotenv IP}}
Device: {{$dotenv DEVICE}}
Browser: {{$dotenv BROWSER}}